app:
    resource: '@AppBundle/Controller/'
    type: annotation

home:
    path:     /
    defaults: {_controller: AppBundle:Default:index}

feeadback:

    path:     /feedback
    defaults: { _controller: AppBundle:Default:feedback }
